version: '3.1'

services:
  chatbot-ner:
    image: chatbot_ner:latest
    build:
      context: .
      dockerfile: Dockerfile-python3
    restart: always
    env_file:
    - .env
    volumes:
    - .:/app/
    ports:
    - 8081:8081
    networks:
    - ner


  neres:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
      - "xpack.security.enabled=false"
    volumes:
    - ./dbdata/esdata/v1:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    networks:
    - ner

networks:
  ner:
    driver: bridge