# ISO 639-1 language codes
HINDI_LANG = 'hi'
ENGLISH_LANG = 'en'
GUJARATI_LANG = 'gu'
BENGALI_LANG = 'bn'
MARATHI_LANG = 'mr'
TELEGU_LANG = 'te'
TAMIL_LANG = 'ta'
URDU_LANG = 'ur'
KANNADA_LANG = 'kn'
ORIYA_LANG = 'or'
MALAYALAM_LANG = 'ml'
PUNJABI_LANG = 'pa'

SPANISH_LANG = 'es'
DUTCH_LANG = 'nl'
FRENCH_LANG = 'fr'
GERMAN_LANG = 'de'

# language translation status
TRANSLATED_TEXT = 'translated_text'

INDIC_LANGUAGES_SET = {HINDI_LANG, TAMIL_LANG, MARATHI_LANG, GUJARATI_LANG, KANNADA_LANG, TELEGU_LANG}
EUROPEAN_LANGUAGES_SET = {SPANISH_LANG, DUTCH_LANG, FRENCH_LANG, GERMAN_LANG}
